version: "3.5"

services:
  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - shopNetwor
    volumes:
      - mongo:/data/db

  
volumes:
    mongo:
        driver: local
networks:
    shopNetwor:
      name: shop-network