version: "3.5"

volumes:
  mongo:
      driver: local
networks:
  shopNetwork:
    name: shop-network
secrets:
  nginx.cert: 
      file: ../ShopApp.Shared/src/ShopApp.Shared/Cert/prod.crt
  nginx.key: 
      file: ../ShopApp.Shared/src/ShopApp.Shared/Cert/prod.key
services:
  products:
    container_name: "production_products"
    environment: 
      - ASPNETCORE_URLS=https://+:5001
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 5001:5001
    build:
      context: ../
      dockerfile: ./ShopApp.Docker/Product/Dockerfile
    depends_on: 
      - mongo
    networks:
      - shopNetwork
  yag:
    container_name: "production_yag"
    environment: 
      - ASPNETCORE_URLS=https://+:50051
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 50051:50051
    build:
      context: ../
      dockerfile: ./ShopApp.Docker/Yag/Dockerfile
    networks:
      - shopNetwork
  # nginx: 
  #   image: nginx:latest
  #   container_name: production_nginx
  #   volumes:
  #     - ..\nginx\nginx.conf:/etc/nginx/nginx.conf
  #     - ..\nginx\error.log:/var/log/nginx/error.log
  #     - ..\nginx\error2.log:/etc/nginx/error2.log
  #   ports:
  #     - 80:80
  #     - 50051:50051
  #   networks:
  #     - shopNetwork
  #   depends_on: 
  #     - products
  #   secrets:
  #     - nginx.cert
  #     - nginx.key      
  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - shopNetwork
    volumes:
      - mongo:/data/db
  sqldata:
    container_name: sqldata
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    networks:
      - shopNetwork 
  client:
    stdin_open: true
    container_name: production_client
    build:
      context: ../
      dockerfile: ./ShopApp.Docker/client/Dockerfile
    environment:
      - REACT_APP_API_GATEWAY=https://localhost:50051
    ports: 
      - 3000:3000
    networks:
      - shopNetwork 
    volumes:
      - ../ShopApp.Shared/src/ShopApp.Shared/Cert/prod.crt:/etc/cert/prod.crt
      - ../ShopApp.Shared/src/ShopApp.Shared/Cert/prod.key:/etc/cert/prod.key
